### ISSUE TITLE
Reasonable values for beta parameter in ATAC-seq chrombpnet run

### ISSUE THREAD

**Issue by gregorydonahue** [jmschrei/bpnet-lite#6]
Hello,

I'm trying to run chrombpnet fit on some ATAC-seq data, but I'm running into an issue. In the step that trains the bias model, during the second tqdm "Loading Loci" progress bar (which I guess is loading the negative sites), numpy throws a ValueError ("ValueError: need at least one array to stack") because of this line in tangermeme/io.py:

    seqs = torch.from_numpy(numpy.stack(seqs))

That's tangermeme/io.py, line 366 in the extract_loci() function.

The immediate reason for the error is that the seqs list is empty. Investigating the loop which populates seqs reveals that every single locus has signal[target_idx].sum() > max_counts, triggering a continue statement. As such, nothing ever gets added to seqs.

After some screwing around, I figured out that max_counts is reset within chrombpnet to be min_counts * beta (at least, this is true for the bias model's negative sites). If I'm thinking about this correctly, the logic makes sense to me, for the negative sites you might want to train only on those within some limited range of ATAC-seq signals. But clearly my data + negatives don't fit within the default range.

Thus, I thought I could get around the error by simply increasing beta from the default of 0.5 to 1, and this does indeed work. But I don't know if this is a good idea - is there some reason not to do this? Can you share any insight on what beta is supposed to represent and whether I can get away with this? What range of values should beta have?

The JSON I'm using is identical to the one in example_jsons/chrombpnet_fit_example.json, but with the "loci", "negatives", "sequences", and "signals" parameters changed to reflect my own data + hg19 reference genome FASTA.

Thanks,
Greg

**Comment by jmschrei** [comment]
Hi Greg

Sorry for the late reply. There are two issues here that have since been resolved in v0.8.0 which you can now get from pip (or cloning the repo).

(1) I was calculating `max_counts` using the minimum number of reads in peaks multiplied by the user-provided beta value. In the ChromBPNet repo they use the 1st percentile instead of true minimum to get a more robust estimate. I now do the same thing. On an internal test setting this caused `max_counts` to increase from 22 to 37 though, obviously, the specific numbers are dataset-specific.

(2) Perhaps more importantly is some confusion in how the JSONs are generated. When you use the `pipeline` or `fit` commands for ChromBPNet, you can pass in a set of parameters for each of the steps. When you don't, these values are taken from the base level of the JSON. When fitting a bias model, if you don't pass in a set of loci to train on it would inherit from the same `loci` keyword that you likely use to specify peaks in the first layer of the JSON. If you were not passing in the negatives to train the bias model then you were basically calculating the minimum number of reads in a peak, then loading up the peaks again and filtering all those that more than half the minimum number of reads in peaks -- by definition, giving you an empty list. I have changed it to instead inherit from `negatives` if you do not provide anything.

Let me know if 0.8.0 works for you.

**Comment by jmschrei** [comment]
Please re-open if issues persist.

**Comment by gregorydonahue** [comment]
Hi Jacob, thanks for responding, I'm just circling back to this now.

I downloaded the latest version of bpnet-lite. While trying to run chombpnet fit, I saw an error where calls to extract_loci() (imported from tangermeme.io) have a new 'ignore' parameter, but tangermeme wasn't updated to accomodate that. Meaning that running this:

    $ chrombpnet fit -p json/ATAC.json

...gives:

    Traceback (most recent call last):
      File "/home/gdonahue/software/MiniConda/miniconda3/envs/bpnetlite2/bin/chrombpnet", line 331, in <module>
        training_data = PeakGenerator(
      File "/home/gdonahue/software/MiniConda/miniconda3/envs/bpnetlite2/lib/python3.8/site-packages/bpnetlite/io.py", line 187, in PeakGenerator
        X = extract_loci(loci=loci, sequences=sequences, signals=signals, 
    TypeError: extract_loci() got an unexpected keyword argument 'ignore'

This happens in chrombpnet and bpnet as well as bpnetlite.io. If you comment out the parameter in the function calls it proceeds as usual. I guess it just filters non-ATGC characters out of the sequences loaded from the FASTA? So if the FASTA is OK then it shouldn't matter.

I'm guessing you're in the process of updating this, so I'll leave this here rather than make a new issue.

Incidentally, there is a typo in the supplied example JSON chrombpnet_fit_example.json, there should be a comma between "chr4" and "chr5" on line 27.

Also, there doesn't appear to be an option for "chrombpnet interpret" (per the documentation on the front page) - I think the relevant operation is called "attribute" there. Actually, now that I think about it, my earlier issue wrt batch size being too large ("Practical limit on # input peaks #7") might have happened because chrombpnet expects to see a block for "attribute" in the JSON and, not finding it, defaults to the enveloping scope parameters (batch_size = 256) or else the hard-coded default value of 64.
